spring:
  application:
    name: spring-cloud-consumer
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
  profiles: peer2

server:
  port: 8200

eureka.client.serviceUrl.defaultZone: http://localhost:8000/eureka/

resilience4j.circuitbreaker:
  instances:
    backendA:
      registerHealthIndicator: true
      slidingWindowSize: 100
    backendB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate

resilience4j.timelimiter:
  instances:
    backendA:
      timeoutDuration: 2s
      cancelRunningFuture: true
    backendB:
      timeoutDuration: 1s
      cancelRunningFuture: false